// Decides which paths Vestry does not document: built-in defaults plus `.vestryignore` (gitignore syntax).
import fs from 'node:fs/promises';
import path from 'node:path';
import ignore from 'ignore';
import { DIR_NAME, IGNORE_FILE } from './constants.js';

const DEFAULT_PATTERNS = [
  `${DIR_NAME}/`,
  '.git/',
  'node_modules/',
  'dist/',
  'build/',
  'out/',
  'target/',
  'coverage/',
  '.next/',
  '*.min.js',
  '*.min.css',
  '*.map',
  // lockfiles
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'bun.lockb',
  'Cargo.lock',
  'poetry.lock',
  'Gemfile.lock',
  'composer.lock',
  'go.sum',
  // binary and media
  '*.png',
  '*.jpg',
  '*.jpeg',
  '*.gif',
  '*.ico',
  '*.pdf',
  '*.zip',
  '*.gz',
  '*.jar',
  '*.class',
  '*.woff',
  '*.woff2',
  '*.ttf',
  '*.mp4',
  '*.wasm',
];

export interface IgnoreMatcher {
  /** true if the repo-relative POSIX path should not be documented */
  isIgnored(relPath: string): boolean;
}

export function createIgnore(userPatterns = ''): IgnoreMatcher {
  const ig = ignore().add(DEFAULT_PATTERNS).add(userPatterns);
  return { isIgnored: (p) => ig.ignores(p.replace(/\\/g, '/')) };
}

export async function loadIgnore(root: string): Promise<IgnoreMatcher> {
  let user = '';
  try {
    user = await fs.readFile(path.join(root, IGNORE_FILE), 'utf8');
  } catch (e) {
    if ((e as NodeJS.ErrnoException).code !== 'ENOENT') throw e;
  }
  return createIgnore(user);
}

/** Generated-file headers (content-based ignore). */
export function looksGenerated(text: string): boolean {
  const head = text.split('\n', 6).join('\n').toLowerCase();
  return /@generated|do not edit|code generated by|auto-generated|autogenerated/.test(head);
}
